### PR TITLE
Use built-in Gradle shorthand notation for Maven Central repository

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by stleary** [comment]
@valfirst Thanks for submitting this PR. What is the purpose of this change? Does it solve a problem?

**Comment by valfirst** [comment]
@stleary 
- `http://repo.maven.apache.org/maven2` - HTTP is not allowed anymore, HTTPS is required:
```
501 HTTPS Required. 
Use https://repo.maven.apache.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```
- instead of managing URLs on the project side Gradle can do it, so in case of some changes it won't be needed to update URLs

**Comment by valfirst** [comment]
More details can be found here: https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by valfirst** [comment]
Complete error:
```
> Task :compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not resolve com.jayway.jsonpath:json-path:2.1.0.
     Required by:
         project :
      > Could not resolve com.jayway.jsonpath:json-path:2.1.0.
         > Could not get resource 'http://repo.maven.apache.org/maven2/com/jayway/jsonpath/json-path/2.1.0/json-path-2.1.0.pom'.
            > Could not GET 'http://repo.maven.apache.org/maven2/com/jayway/jsonpath/json-path/2.1.0/json-path-2.1.0.pom'. Received status code 501 from server: HTTPS Required
   > Could not resolve org.mockito:mockito-core:1.9.5.
     Required by:
         project :
      > Could not resolve org.mockito:mockito-core:1.9.5.
         > Could not get resource 'http://repo.maven.apache.org/maven2/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.pom'.
            > Could not GET 'http://repo.maven.apache.org/maven2/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.pom'. Received status code 501 from server: HTTPS Required
```

**Comment by stleary** [comment]
No objection to the change, but I cannot recreate the error. Can you provide recreate steps please?

**Comment by valfirst** [comment]
@stleary most likely you have the dependencies cached in your maven local repo or Gradle cache or even both, so you need 
- to clear local caches
or
- to change the caches location (temporarily)
or
- use clean machine (container)
to reproduce the error just by running `./gradlew build`

**Comment by stleary** [comment]
It seems reasonable to make this change.

**Comment by stleary** [comment]
**What problem does this code solve?**
Gradle builds may fail on Maven download. This may occur if the device has never downloaded the Maven files previously.

**Risks**
Low

**Changes to the API?**
No

**Will this require a new release?**
No

**Should the documentation be updated?**
No

**Does it break the unit tests?**
No

**Was any code refactored in this commit?**
No

**Review status**
**APPROVED**
Starting 3 day comment window.

**Pull request merged**
