### PR TITLE
Added some examples for new-comers in a Markdown file

### PR DESCRIPTION
**Pull request by TheNeoStormZ**
I have made a simple Java file (JSONExamples.java, ubicated in src/main/java/org.json) in which i explain how to get started with all the JSON-types and how to use all conversors to new-comers.

### CODE REVIEW

**Comment by kushieda-minori** [comment]
Please rename the file `EXAMPLES.md` and place in the root of the project. Also surround the code with

    ```java
    package org.json;
    import java.util.HashMap;
    import java.util.Map;
    import java.util.Properties;
    
    //This class' intention is to explain to new-comers the basics of this project
    public class JSONExamples {
        // ACTUAL EXAMPLES HERE
    }
    ````

We don't really want the examples compiled into the release jar. Having it as a Markdown file will also make it easy to read.

**Review by johnjaylward — CHANGES_REQUESTED** [review]
move to a markdown file.

**Comment by TheNeoStormZ** [comment]
Done! It should be changed now. I have also tweaked the file a little bit so it looks good in Markdown

**Comment by stleary** [comment]
**What problem does this code solve?**
Project needs documentation to help new users come up to speed.

**Risks**
None, but need to review the code for syntax, clarity, completeness.

**Changes to the API?**
No

**Will this require a new release?**
No

**Should the documentation be updated?**
Yes, the new markdown file will need to be navigable from the README.

**Does it break the unit tests?**
No

**Was any code refactored in this commit?**
No

**Review status**
In review

**Comment by stleary** [comment]
@TheNeoStormZ  Nice work, thanks for putting in the effort. 

This PR is approved. Noting here some possible improvements for future pull requests:

- I think JSONExampleTokener is incomplete, throws an exception.
- JavaDocs should be written for the functions
- An enclosing class should be provided, e.g. JSONJavaDemo.
- .md headers and text should be commented, so that users can easily copy and paste the entire document into a Java file. For example, `// Part 2: Conversion methods`
- The function calls in main() should all be uncommented
- Additional text should be provided explaining the purpose of each class.
- Text should be included on how to compile and run this code
- Add these mandatory imports:
````
import org.json.CDL;
import org.json.Cookie;
import org.json.HTTP;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONStringer;
import org.json.JSONTokener;
import org.json.JSONWriter;
import org.json.Property;
import org.json.XML;
````

**Pull request merged**
