### PR TITLE
Issue 682 JSONString similarity

### PR DESCRIPTION
**Pull request by spaffrath**
For Issue #682.

What problem does this code solve?
The `similar` methods of JSONObject and JSONArray did not evaluate two equivalent JSONString objects to true.

Risks
Low

Changes to the API?
No

Will this require a new release?
No

Should the documentation be updated?
No

Does it break the unit tests?
No, new unit tests were added.

Was any code refactored in this commit?
No

Review status:
**APPROVED**

### CODE REVIEW

**Comment by johnjaylward** [comment]
@stleary it looks like we may have an incorrect version of something in the maven build configuration:

```
2022-08-05T19:07:53.5945505Z [WARNING] Error injecting: org.apache.maven.plugins.surefire.report.SurefireReportOnlyMojo
2022-08-05T19:07:53.5946593Z java.lang.TypeNotPresentException: Type org.apache.maven.plugins.surefire.report.SurefireReportOnlyMojo not present

2022-08-05T19:07:53.6075845Z Caused by: java.lang.UnsupportedClassVersionError: org/apache/maven/plugins/surefire/report/SurefireReportOnlyMojo : Unsupported major.minor version 52.0
```

@spaffrath you are correct it's not related to the changes, however you may be able to fix the issue by updating the `POM.xml`. It looks like one or more of the plugins is having a version conflict.

**Comment by stleary** [comment]
I can take a look at this tonight.

**Comment by stleary** [comment]
See #684 
You can make the same change on your branch, or wait for the merge to master, and then merge master to your branch and try again.

**Review by stleary — APPROVED** [review]

**Comment by stleary** [comment]
Starting 3 day comment window

**Pull request merged**
