### PR TITLE
JSONTokener implemented java.io.Closeable

### PR DESCRIPTION
**Pull request by haribabu-dev**

### CODE REVIEW

**Comment by stleary** [comment]
Why should JSONTokener implement Closeable? It is not a closeable resource. Can you just add the close() method without the override or interface?

**Comment by haribabu-dev** [comment]
Ok @stleary , I will do that.

**Comment by stleary** [comment]
**What problem does this code solve?**
Users may want to close the reader associated with a JSONTokener

**Risks**
Low

**Changes to the API?**
A new public API function was added, with unit test

**Will this require a new release?**
No

**Should the documentation be updated?**
No

**Does it break the unit tests?**
No

**Was any code refactored in this commit?**
No

**Review status**
**APPROVED**


Starting 3-day comment window

**Review by stleary — APPROVED** [review]

**Comment by jtotht** [comment]
> @haribabu-dev Why should JSONTokener implement Closeable? It is not a closeable resource. Can you just add the close() method without the override or interface?

Because it (potentially) uses closable resources. See #718, which would have been closed by the original version of this PR, but not the one that got merged.

**Pull request merged**
