### PR TITLE
Fixes Issue #611 JsonObject.similar() returns after number entry check

### PR DESCRIPTION
**Pull request by stleary**
#611 reported that similar returns too soon on success when a Number entry type is checked. Fixed by returning only if the Number check fails. Added unit test to exercise the new code.

### CODE REVIEW

**Comment by stleary** [comment]
**What problem does this code solve?**
Fixes #611 similar() returns too soon when checking Number entries

**Risks**
Low

**Changes to the API?**
No

**Will this require a new release?**
No

**Should the documentation be updated?**
No

**Does it break the unit tests?**
No, but a unit test was added 

**Was any code refactored in this commit?**
No

**Review status**
**APPROVED** - By myself

Starting 3 day comment window

**Review by johnjaylward — CHANGES_REQUESTED** [review]
Please also correct the implementation in `JSONArray`

**Comment by johnjaylward** [comment]
Also, due to the nature of the bug fix, this probably should get a new release.

**Comment by stleary** [comment]
Forgot to check JsonArray, thanks for the heads-up @johnjaylward.
Agreed this is a good release candidate.

**Pull request merged**
