### PR TITLE
Added clear() methods to JSONObject and JSONArray

### PR DESCRIPTION
**Pull request by stranck**
I noticed that there wasn't this easy way to clear all the childs of a JSONObject or a JSONArray, so I added it.
Changes in code are really simple

### CODE REVIEW

**Comment by stleary** [comment]
@stranck Thanks for submitting this PR. The submitter is usually asked to provide a use case or justification, but I guess in this case it is self-evident. No objection to proceeding after you add the appropriate unit tests.

**Comment by stranck** [comment]
I should've added them :)
Tell me if they're alright and thank you for being so fast in replying ahahahhaha

**Comment by stleary** [comment]
**What problem does this code solve?**
This is an enhancement to include a missed clear() method, not a bug fix. The API includes JSONObject and JSONArray methods that recognize they are containers, so adding this method makes sense. 

**Risks**
Low

**Changes to the API?**
New public methods are added to JSONObject and JSONArray

**Will this require a new release?**
No

**Should the documentation be updated?**
No

**Does it break the unit tests?**
No, new unit tests were added

**Was any code refactored in this commit?**
No

**Review status**
**APPROVED**

**Comment by stleary** [comment]
Starting 3 day comment window

**Pull request merged**
