### PR TITLE
comment out some broken unit tests

### PR DESCRIPTION
**Pull request by stleary**
**gradlew -version**
Gradle 6.3
Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60
Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_05 (Oracle Corporation 25.5-b02)
OS:           Windows 8.1 6.3 amd64

**gradlew clean build test**
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 5s
9 actionable tasks: 9 executed

**mvn -version**
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T15:58:10-05:00)
Maven home: c:\apache-maven-3.2.3\bin\..
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_05\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"

mvn clean test
...
Tests run: 314, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.673 s
[INFO] Finished at: 2020-06-03T21:23:14-05:00
[INFO] Final Memory: 24M/114M
[INFO] -----------------------------------------------------------------------

**APPROVED - by me**

### CODE REVIEW

**Comment by johnjaylward** [comment]
@stleary, this shouldnt be needed if you delete https://github.com/stleary/JSON-java/blob/master/src/test/java/org/json/junit/JunitTestSuite.java and https://github.com/stleary/JSON-java/blob/master/src/test/java/org/json/junit/TestRunner.java

**Comment by johnjaylward** [comment]
I meant to remove them in #525, but must not have pushed that commit

**Comment by stleary** [comment]
@johnjaylward no objection if you want to remove TestRunner and JunitTestSuite if the PR includes instructions for running all of the unit tests at once successfully from Eclipse. For now Eclipse with Java 1.8 is sufficient.

**Comment by johnjaylward** [comment]
There are no special instructions. Removing those files prevents eclipse from running the tests twice. They always ran fine before using gradle or maven

**Comment by stleary** [comment]
I removed the files and am still getting errors in Eclipse with Java 1.8, from XMLTest, JSONObjectTest, and XMLConfigurationTest. I believe that most or all are JSONObject ordering problems. I think someone mentioned that in another thread. The next accepted PR should address Eclipse with Java 1.8 test failures. After that Java 1.7 for Gradle, Maven, and Eclipse. Finally, Java 1.6 for all 3 builds. If you think some or all of this is unnecessary, please let me know your reasoning.

**Pull request merged**
