### PR TITLE
#459 Fixing indendation of printing JSON objects

### PR DESCRIPTION
**Pull request by anandvarkeyphilips**
An attempt to enhance existing pretty print functionality.

### CODE REVIEW

**Comment by anandvarkeyphilips** [comment]
> Does this add new lines to the compact output?

@johnjaylward  No, I had missed that scenario. I have updated the code to handle it now. Please review and accept. :)

**Comment by stleary** [comment]
@anandvarkeyphilips -

- You did not modify JSONArray.java. Are you omitting new indent handling in arrays for a reason?
- Breaks unit tests in [JSON-Java-unit-test](https://github.com/stleary/JSON-Java-unit-test)

**Comment by anandvarkeyphilips** [comment]
@stleary , I didnt feel it was required. All appeared good.
Can you test here and advice on what to do?
http://varkeys-rhel-jenkins.westus.cloudapp.azure.com:8090/editor

**Comment by stleary** [comment]
@anandvarkeyphilips Thanks for adding this enhancement to formatted output. Here is a more complete explanation of what still needs to be done.
- JSONArray formatting may not be important for your use case, but consistent handling of JSON objects and arrays is usually a good idea, and others may find it helpful as well. It sounds like you did not specifically omit updating the JSONArray code. In that case, please consider making the same change to both classes, or explain why the JSONArray code should not be changed.  
- Please check the [FAQ for unit tests](https://github.com/stleary/JSON-java/wiki/FAQ#where-are-the-unit-tests). Your changes have broken the unit tests, and can't be accepted until the tests are fixed. No exceptions on this rule. The changes needed are straightforward, but you will need to submit a pull request on the unit test repository, which will be committed along with this change. Let me know if you have any questions about how to proceed.

**Comment by stleary** [comment]
Closing due to no activity in the past 2 months.

**Pull request closed without merging**
