### PR TITLE
Unit test fixes

### LINKED ISSUE #523: Unit tests appear to be broken - recent merge?
**Top priority  - get the unit tests working again. Needs to be working by EOD 6/3/2020**
Unit tests now working for gradle 6.3 with Java 1.8, and maven 3.2.3 with Java 1.8.

**Before any more PRs can be accepted:**
* Code and unit tests have to compile and execute using Java 1.6 - 1.8 **1.8 completed**
* Gradle builds need to work, with documentation suitable for new developers on how to get it running. **Completed sufficently for now, docs pending**
* Maven builds need to work, with documentation suitable for new developers on how to get it running. **Completed sufficently for now, docs pending**
* Eclipse builds need to work, with documentation. Optionally, if anyone has gotten this to work with IntelliJ, that would be welcome as well.
* Documentation for how a person will little prior experience can manually find, compile, and use the lib files.
* Restore unit tests in JSONObjectTest: 
* * testSingletonBean()
* * testSingletonEnumBean()

### PR DESCRIPTION
**Pull request by johnjaylward**
**What problem does this code solve?**
Fixes #523 
* Adds Gradle wrapper for easier use of the gradle build tool
* Removes "Test Suite" configuration class and the "main" 

**Risks**
None. No changes to library code, just supporting items

**Changes to the API?**
No

**Will this require a new release?**
No

**Should the documentation be updated?**
No

**Does it break the unit tests?**
No

Was any code refactored in this commit?

Review status

### CODE REVIEW

**Comment by stleary** [comment]
@johnjaylward  gradle-wrapper.properties specify gradle-6.3, but the test case was fixed in Java 1.7? Can you clarify?

**Comment by johnjaylward** [comment]
The test case was using a function that wasnt available until java8. I chamaged it to not use that function and instead use manual casting and addition

**Comment by stleary** [comment]
**APPROVED**
Thanks for the quick effort! A couple more failing tests, but this gets Gradle back in play.

**Comment by johnjaylward** [comment]
Yes, from my testing here: https://github.com/johnjaylward/JSON-java/actions you can see that most of the tests fail in Java7 due to comparison differences due to hash reordering.

**Pull request merged**
