### PR TITLE
Revert "reduces the use of unnecessary exceptions"

### PR DESCRIPTION
**Pull request by stleary**
Reverts stleary/JSON-java#249

### CODE REVIEW

**Comment by johnjaylward** [comment]
@stleary I don't think this was necessary. See my comment on #260

**Comment by stleary** [comment]
**What problem does this code solve?**
#249 was supposed to be a minor refactoring, but it contains an uncaught bug that breaks the opt*() methods. It needs to be reverted,

**Changes to the API?**
No change to the API

**Will this require a new release?**
Yes, the 20160807 Maven release contains this bug.

**Should the documentation be updated?**
Not required

**Change to unit tests?**
No changes for the revert, but new unit tests will be added later.

**Note**
This pull request is being fast-tracked, so if you have comments, get them in quickly. Will leave the request open for 1 day.

**Comment by johnjaylward** [comment]
@stleary looking at the reversal, this does not solve the issue.

**Comment by stleary** [comment]
@johnjaylward please elaborate.

**Comment by johnjaylward** [comment]
the functions optBoolean, optLong, optInt, etc were calling the get method internally before the original changes were made that this is reverting.

**Comment by johnjaylward** [comment]
https://github.com/stleary/JSON-java/blob/master/JSONObject.java#L513

it is still calling get() without a try-catch block, so the issue in #260 is not solved.

**Comment by johnjaylward** [comment]
oh nevermind. I thought this was merged already, but I now see it's not. I was mistaken when I saw the closed status above.

**Comment by stleary** [comment]
No worries, let me know if you see any other reason not to revert, am otherwise strongly inclined to proceed.

**Comment by johnjaylward** [comment]
I ran the tests against the reverted branch just now, and they all seem to pass, while there are failures on master. At this time I see no reason to hold the revert.

**Comment by johnjaylward** [comment]
You may want to just add a new commit after the revert to correct the comment fixes that @Simulant87 made in #249. Those are valid fixes.

**Comment by Simulant87** [comment]
@johnjaylward is right. changing

`this.get(key);`

to

`this.opt(key);`

in all the optXXX methods fixes the bug. I think I can submit a new merge-request to fix this bug in 12 hours, if you can wait for this. Otherwise someone else can do the fix.

**Pull request merged**
