### PR TITLE
Update pipeline.yml

### PR DESCRIPTION
**Pull request by javadev**
Added support for java 17

### CODE REVIEW

**Comment by stleary** [comment]
Looks like there are build issues.

**Comment by javadev** [comment]
> Looks like there are build issues.

Error: [ERROR] error: Source option 6 is no longer supported. Use 7 or later.
Error: [ERROR] error: Target option 6 is no longer supported. Use 7 or later.

**Comment by javadev** [comment]
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.418 s
[INFO] Finished at: 2023-02-05T02:54:06Z
[INFO] ------------------------------------------------------------------------
0s
Run actions/upload-artifact@v[1](https://github.com/stleary/JSON-java/actions/runs/4094583582/jobs/7060972741#step:7:1)
Error: Path does not exist /home/runner/work/JSON-java/JSON-java/target/surefire-reports/
Error: Exit code 1 returned from process: file name '/home/runner/runners/2.301.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.

**Comment by javadev** [comment]
The same error for java 17 compiler

Error: [ERROR] error: Source option 6 is no longer supported. Use 7 or later.
Error: [ERROR] error: Target option 6 is no longer supported. Use 7 or later.

**Pull request closed without merging**
