### PR TITLE
Fix negative zero

### LINKED ISSUE #187: JSONTokener recognizes -0 as a string not as a number, based on usage from json-schema
See: https://github.com/everit-org/json-schema/issues/25

### PR DESCRIPTION
**Pull request by johnjaylward**
Fixes #187 -0 now returns as a double.

### CODE REVIEW

**Comment by johnjaylward** [comment]
test cases subbmitted

**Comment by stleary** [comment]
**What problem does this code solve?**
Parser should follow the JSON spec and produce numeric values from '-0' and '-0.0'
This is a user-found defect. See issue https://github.com/stleary/JSON-java/issues/187. 

**Changes to the API?**
*XML.stringToValue(String)* is deprecated in favor of *JSONObject.stringToValue(String)*

**Changes to how the code behaves?**
Negative zero strings are now parsed to Long or Double instead of String.

**Does it break the unit tests?**
No, but new unit tests will be committed after this code is committed. See https://github.com/stleary/JSON-Java-unit-test/pull/39.

**Will this require a new release?**
No, I am proposing for this change to be be rolled into the next release. If you disagree, please
post in this thread

**Should the documentation be updated?**
No.

**Comment by johnjaylward** [comment]
-0 and -0.0 both parse to Double since Long/Integer would lose the sign.

**Comment by stleary** [comment]
Got it, thanks.

**Comment by coderextreme** [comment]
This fixed over 6300 instances in our JSON documents.   Thanks everyone for the effort.

**Pull request merged**
