### PR TITLE
Adding maven badge to readme

### PR DESCRIPTION
**Pull request by fleipold**
This PR converts the README file to markdown and adds a maven badge, so that the latest version is immediately visible. 

Somewhat like this:
image

It also adds a little bit of markdown syntax maintain a reasonable appearance (.md-files get rendered in non-fixed font by default).

### CODE REVIEW

**Comment by johnjaylward** [comment]
@stleary, it may finally make sense to have the markdown version. Having those "badges" at the top can be handy.

**Comment by stleary** [comment]
@johnjaylward Agreed, a markdown readme would be a helpful improvement.
@fleipold please change the class name highlighting from inline-code to bold. The badge is good, but please move it to the bottom of page. 
@anyone - additional comments or suggestions are welcome.

**Comment by fleipold** [comment]
@stleary Thanks for the quick feedback. I am happy to move the badge around and to make the class names bold. However there seems to be a convention to have the badges at / near the top. What do you think?

I will not get to this until the end of the week anyway, so I'll check for more feedback and could then incorporate that too.

**Comment by stleary** [comment]
@fleipold yes badge at the top is OK.

**Comment by fleipold** [comment]
@stleary I have made the file names (not the class names). Is that ok for you? I also made a couple of links markdown links. Let me know what you think.

**Comment by stleary** [comment]
@fliepold Apologies, I got out of sync on this. Please submit the pull request if you still want to commit this change. The updates you have described should be fine.

**Comment by fleipold** [comment]
@stleary No worries. To me it looks like this pull request is still up-to-date, so you should be able to merge it by clicking the merge button (you can also squash all the commits into one, I just made a lot of commits for clarity, but perhaps they shouldn't go to the master). The options how to merge a pull request are described here: https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github

**Comment by stleary** [comment]
Thanks for the refresher :) PR will be merged soon, pending comment window.

**Comment by stleary** [comment]
**What problem does this code solve?**
Not a bug fix or enhancement, just improving the Readme.

**Risks**
N/A

**Changes to the API?**
N/A

**Will this require a new release?**
N/A

**Should the documentation be updated?**
This is part of the documentation

**Does it break the unit tests?**
N/A

**Was any code refactored in this commit?**
N/A

**Review status**
**APPROVED** Staring 3 day window for comments

**Pull request merged**
