### PR TITLE
stream.Collector initialized + some updates

### PR DESCRIPTION
**Pull request by AmirHossein**
For JSONObject and JSONArray

### CODE REVIEW

**Comment by johnjaylward** [comment]
the java-1.8 branch was created for reference only on a historical commit that broke backwards compatibility. At this time there is no case for requiring java1.8 but there are use cases for maintaining 1.6 compatibility.

In the future, you should only apply merge requests against the **master** branch and not side branches.

Also, you should either disable auto formatting in your IDE or update the settings to match the OSS project that you are contributing to.

**Comment by AmirHossein** [comment]
@johnjaylward i knew that the project has 1.6 compatibilities and 1.8 updates won't be merged to master so i just wanted to push some updates as a 1.8 fork of project for anybody needs.

**Comment by stleary** [comment]
I suppose we could maintain 2 release trains; one for 1.6 and another for 1.8 that is functionally identical. But this pull request contains files which are not even in the build anymore. If you really want to do this, consider taking the latest 1.6 code and adding your 1.8 code to it. If it looks reasonable, maybe a new branch can be created for it.

**Comment by AmirHossein** [comment]
@johnjaylward Currently the long commits list above are for merging with master and just last 3 commits are mine

**Comment by stleary** [comment]
Thanks for the pull request. The idea is reasonable, but can't be accepted in its current form.

**Pull request closed without merging**
