### PR TITLE
#688 update copyright 

### PR DESCRIPTION
**Pull request by stleary**
**What problem does this code solve?**
Replaces license and copyright with Public Domain throughout the repo, per request of the author.

**Risks**
None

**Changes to the API?**
No

**Will this require a new release?**
No

**Should the documentation be updated?**
Yes - check the FAQ

**Does it break the unit tests?**
N/A

**Was any code refactored in this commit?**
N/A

**Review status**
**APPROVED** - by myself

### CODE REVIEW

**Comment by stleary** [comment]
Starting 3-day comment window.

**Comment by soundasleep** [comment]
Thank you so much for this license change!!

May I suggest using one of the following licenses instead of "public domain" just to make sure it's clearly public domain, and so automated tools can reliably pick up the change?

- CC0: https://creativecommons.org/share-your-work/public-domain/cc0/
- 0BSD: https://opensource.org/licenses/0BSD
- MIT-0: https://github.com/aws/mit-0

**Comment by stleary** [comment]
@douglascrockford In case this is of interest to you.

**Comment by m0hamed** [comment]
I would also like to support using a more common public domain license like CC0

**Comment by sonots** [comment]
I also like a more common public domain license like CC0

**Comment by BlueSkyDetector** [comment]
Some countries, for example Japan, have no definition of Public Domain in law.  
So, more common public domain license like CC0 is preferable.

**Comment by stleary** [comment]
The original author of the application, Douglas Crockford, selected the license. Please reach out to him if you would like to see any changes.

**Pull request merged**
