### PR TITLE
Either log or rethrow otherwise invisible Exceptions.

### PR DESCRIPTION
**Pull request by Mormuig**
When possible, just put the original Exception as the cause of thrown
JSONException.
Using log to give possibility to trace other exceptions, with FINE level
so they don't show up in a default configuration (default ConsoleHandler
log from INFO to SEVERE).
Linked to #237 issue.

### CODE REVIEW

**Comment by Mormuig** [comment]
It use standard Java Logging, so it should not error in a standard JRE.
The default output is console (defined by the root logger ConsoleHandler), but it can be changed either by config file or incode.

**Comment by stleary** [comment]
Thanks, looks good. 

It would be helpful to have some text that describes concrete scenarios about how someone would make use of the new code. For example:

- How to configure logging in order to view an ignored exception, with a code fragment that causes the exception
- Are there any considerations, and how to set up the logging config for executing the code in an IDE (e.g. Eclipse)

I don't think that most of the changed code is exercised by the unit tests: https://github.com/stleary/JSON-Java-unit-test. I can do this when time permits. But if you have time and want to add the unit tests, that would help move things along.

**Comment by Mormuig** [comment]
Here is an example with the code of the referenced issue.
In this example, no other configuration is needed, it while show in the IDE console while executing the main method.
I will provide another example using a file configuration.

```
package main;

import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.json.JSONObject;

public class MainInCode {

    public static void main(String[] args) {

        // Nothing logged, just print an empty JSONObject
        System.out.println(new JSONObject(new Test(), new String[] { "message" }));

        // Get the logger associated with JSONObject
        Logger logger = Logger.getLogger(JSONObject.class.getName());
        // Setting the log Level to FINE (INFO is default)
        logger.setLevel(Level.FINE);
        // Tell the logger to not use the parents Handlers
        logger.setUseParentHandlers(false);

        // Creating a new ConsoleHandler (could be any handler)
        ConsoleHandler console = new ConsoleHandler();
        // Setting the log level of this Handler to FINE
        console.setLevel(Level.FINE);

        // Associate the two
        logger.addHandler(console);

        // Error logged, and still print the empty JSONObject
        System.out.println(new JSONObject(new Test(), new String[] { "message" }));
    }

    // non-public class
    static class Test {
        public String message = "test";
    }
}
```

**Comment by johnjaylward** [comment]
I don't think there is a good way to test loggers short of writing your own "test" implementation to the interface that will trigger something.

@stleary , these changes look good to me as long as they aren't breaking any tests. The changes don't appear to change any logic flow.

**Comment by stleary** [comment]
@johnjaylward, no objection to proceeding, unit tests are still needed.

**Comment by Mormuig** [comment]
I used a StreamHandler on the Logger to catch emitted logs.
I'm working on the normally unreachable logs (those in catch block), hope to be done shortly.

**Comment by johnjaylward** [comment]
@Mormuig I incorporated the exception wrapping changes into the latest master.  If you can merge or rebase your PR we can look at just the logging changes then.

**Comment by stleary** [comment]
Thanks for the pull request, but can't be accepted at this time.

**Pull request closed without merging**
