### PR TITLE
Fixes for Unit tests and supports GitHub Actions

### LINKED ISSUE #523: Unit tests appear to be broken - recent merge?
**Top priority  - get the unit tests working again. Needs to be working by EOD 6/3/2020**
Unit tests now working for gradle 6.3 with Java 1.8, and maven 3.2.3 with Java 1.8.

**Before any more PRs can be accepted:**
* Code and unit tests have to compile and execute using Java 1.6 - 1.8 **1.8 completed**
* Gradle builds need to work, with documentation suitable for new developers on how to get it running. **Completed sufficently for now, docs pending**
* Maven builds need to work, with documentation suitable for new developers on how to get it running. **Completed sufficently for now, docs pending**
* Eclipse builds need to work, with documentation. Optionally, if anyone has gotten this to work with IntelliJ, that would be welcome as well.
* Documentation for how a person will little prior experience can manually find, compile, and use the lib files.
* Restore unit tests in JSONObjectTest: 
* * testSingletonBean()
* * testSingletonEnumBean()

### PR DESCRIPTION
**Pull request by johnjaylward**
**What problem does this code solve?**

Fixes #523 
* Fixes tests running in Eclipse. Simply right-click and select "Run As -> JUnit Test"
image
* Restore unit tests in JSONObjectTest
* Uses work from @viveksacademia4git to get basic GitHub Actions working so test cases are auto-run for merge requests

**Risks**
LOW/None. Only Tests were corrected

**Changes to the API?**
No

**Will this require a new release?**
No

**Should the documentation be updated?**
No

**Does it break the unit tests?**
No, it fixes them

**Was any code refactored in this commit?**
Only Test cases to make the items being tested simpler to follow and verify.

**Review status**
**APPROVED**
No comment window this time

### CODE REVIEW

**Comment by stleary** [comment]
Confirmed successful build and unit test with gradle 6.4, maven 3.2.3, Eclipse Luna, Java 1.8.0_05.
Unit tests were also successful in Eclipse with Java 1.6 and 1.7.

**Comment by stleary** [comment]
Thanks, nice work. Will check GitHub actions on the next PR.

**Comment by johnjaylward** [comment]
You can see what it looks like now

https://github.com/stleary/JSON-java/actions/runs/126495486

It ran the jobs after you merged

**Comment by stleary** [comment]
I get that is runs on PR, but was not expecting it to run on commit:
````
on:
  push:
    # branches: [ master ]
  pull_request:
    branches: [ master ]
````

**Comment by johnjaylward** [comment]
With the `push.branches` qualifier commented, it will run on a push to any branch. Since I was testing it on a non-master branch in my fork, I commented that out.

It looks like github lets you create as many of these job files as you want, so you should be able to create one that triggers when a tag is created and then does the push to maven central for you.

**Comment by johnjaylward** [comment]
As a side note, the secret key for deployment would go in the project settings -> secrets area, which only you would have access to

https://github.com/stleary/JSON-java/settings/secrets

**Pull request merged**
