### PR TITLE
Added stream function to JSONArray

### PR DESCRIPTION
**Pull request by aghasemi**
Added stream function to JSONArray in order to obtain similar functionality to Java collections

### CODE REVIEW

**Comment by erosb** [comment]
This would be a very nice improvement, but I'm afraid this can't be merged, because it breaks java6 compatibility.

**Comment by aghasemi** [comment]
Oops. Ok. So there is no plan to drop Java6 support in the future? I'll be back then.

**Comment by johnjaylward** [comment]
there is no plan at this time, but it is expected to happen eventually. Since JSONArray implements Iterable, you should be able to create a stream using the StreamSupport class:

```java
JSONArray myArray = new JSONArray();
// add some elements to the array somehow

java.util.stream.StreamSupport.stream(new JSONArray().spliterator(), false);
```

**Comment by aghasemi** [comment]
How about adding a `toList()` method or something like that? Then we have streams as well.

**Comment by johnjaylward** [comment]
Personally, I don't even like our Iterator support. It offers raw access to the underlying type without any of the checks/conversions to JSON Types. It should be used sparingly with the understanding that the underlying object may not come back as an expected type.

**Comment by aghasemi** [comment]
But then integration with the "rest " of Java will be way easier.

**Comment by johnjaylward** [comment]
I'm not sure what you mean by that. I also don't see why having a toList method would be any better than the first option I provided using StreamSupport.

**Comment by MinnDevelopment** [comment]
Unless I'm mistaken there already is a toList: https://github.com/stleary/JSON-java/blob/d402a99fd87dc5c5d20f24342656237b18629838/JSONArray.java#L1477-L1500

**Comment by aghasemi** [comment]
Yes that's true. My bad.

**Comment by stleary** [comment]
Thanks for the pull request, but cannot be accepted at the present time. Please see https://github.com/stleary/JSON-java/wiki/FAQ#what-version-of-java-does-this-project-require

**Pull request closed without merging**
